### ISSUE TITLE
Seems to have issues with IO::Socket::IP again

### ISSUE THREAD

**Issue by moltar** [olegwtf/p5-IO-Socket-Socks-Wrapper#3]
It looks like it works with `IO::Socket::IP` version 0.35, but stops working at 0.36 and 0.37.

**Comment by olegwtf** [comment]
Don't see any significant changes since 0.35, which may cause problems. Can you provide example for test?

**Comment by moltar** [comment]
https://github.com/moltar/io-socket-ip-test

**Comment by olegwtf** [comment]
Can't confirm problems with your test, all works as expected with both 0.36 and 0.37 and latest versions of HTTP::Tiny, IO::Socket::Socks and IO::Socket::Socks::Wrapper. What versions do you have?

**Comment by moltar** [comment]
You can see exact versions used for test here: https://github.com/moltar/io-socket-ip-test/blob/master/cpanfile.snapshot

Did you actually test exactly like described in the README? Did you use carton? I think that's important to isolate the issue.

**Comment by olegwtf** [comment]
Is changing "localhost" to "127.0.0.1" fixes this problem for you?

**Comment by moltar** [comment]
Ha! It does! What's the explanation?

Thank you!

**Comment by olegwtf** [comment]
Don't know. Need a little more debugging. Will write my investigations here before closing this report.

**Comment by moltar** [comment]
Could be something with IPv6? On Mac, localhost resolves to both by default:
```
127.0.0.1       localhost
::1             localhost
```

**Comment by olegwtf** [comment]
My investigations resulted in bug report for IO::Socket::IP https://rt.cpan.org/Ticket/Display.html?id=112334 and new version of IO::Socket::Socks https://metacpan.org/release/OLEG/IO-Socket-Socks-0.68
All should work when this IO::Socket::IP bug will be fixed.

**Comment by moltar** [comment]
Very cool. Thank you, Oleg! Спасибо!
