### ISSUE TITLE
telnet timeouts not returning correctly

### ISSUE THREAD

**Issue by dschwartz33** [olegwtf/p5-IO-Socket-Socks-Wrapper#4]
First, my apologies if this is addressed in a newer version - we have 
IO::Socket:Socks v. 0.67
IO::Socket::Socks::Wrapper v. 0.14

The wrapper is applied globally before any other connection related libs are included:

	require IO::Socket::Socks::Wrapper;
	IO::Socket::Socks::Wrapper->import({ProxyAddr => $Socks5Host,
		ProxyPort => $Socks5Port,
		Timeout => 30,
		SocksDebug => 0});

The file where this happens calls a second file that loops over connecting to a number of devices with the following code:
         use Net::Telnet;

		my $telnet = new Net::Telnet(
			Timeout => 2,
			Cmd_remove_mode => 1,
			Errmode => 'return',
			Dump_Log => $DebugLog,
			Prompt => '/-->\s*$/i'
		);
		my $error;
		# Ok, open the connection
		if(!$telnet->open($self->{'ip'})) {
			$error="Could not connect to ONT ($self->{'ip'}) - " . $telnet->errmsg();
			return (0,$error);
		}

If any of these devices happen to not be online, and open() times out, it does not return $error, but instead exits back to the first file.

**Comment by olegwtf** [comment]
This should be fixed by https://github.com/olegwtf/p5-IO-Socket-Socks-Wrapper/commit/d75f1599d4186f5cd91cee14b5011275b1f5e1d3

Please check with version from this repository

**Comment by dschwartz33** [comment]
Yep, that fixes it - thanks!!!
