### ISSUE TITLE
How to avoid local Name Resolution?

### ISSUE THREAD

**Issue by seppovic** [olegwtf/p5-IO-Socket-Socks-Wrapper#5]
Hello and my appologies for stealing your time with this probably stupid question, I am not into Network Programming at all.^^

The Problem I am trying to solve is about connecting to a LDAP Server through a Socks Proxy, with no local name Resolution possible.

here is the relevant code:
`IO::Socket::Socks::Wrapper->import(
	'Net::LDAP::connect_ldap()' => {
		ProxyAddr  => $proxy,
		ProxyPort  => $proxy_port,
		Timeout    => 5,
		SocksDebug => 0
	}
);
my $ldap = Net::LDAP->new($ldap_uri);
if (!$ldap) {
	_debug(2, "could not establish connection: $@");
	return 0;
}
`
I thought that the name Resolution is automatically done by the Proxy Server, but i get this Error from my debug output
`...could not establish connection: IO::Socket::INET: Bad hostname 'somehost.com'`

Setting local names in /etc/hosts does solve that issue but its not the way it should work. 
Am I using your module wrong or do i have to lookup the names before hand through the proxy and pass the ip to ldap connection?

Thank you very much in advance.

**Comment by olegwtf** [comment]
Hello. You need `SocksResolve` option. See https://metacpan.org/pod/IO::Socket::Socks#new(-%25cfg-) for full list of options.

**Comment by seppovic** [comment]
Thank you very much for your quick response and help.

I found the time to test that, but didn't solve the problem.
As the doc states, $SOCKS5_RESOLVE variable is set to true by default, I guess there is something wrong in the infrastructure, I will have a look in that direction before I come back.
closing this for now because I dont think there is anything wrong with the module.

cheers
